import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val navigation_fragment_ktx: String = "android.arch.navigation:navigation-fragment-ktx:" +
            Versions.android_arch_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val navigation_ui_ktx: String = "android.arch.navigation:navigation-ui-ktx:" +
            Versions.android_arch_navigation

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val annotation: String = "androidx.annotation:annotation:" + Versions.annotation

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://tools.android.com */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val androidx_core_core: String = "androidx.core:core:" + Versions.androidx_core_core

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.androidx_fragment

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val fragment: String = "androidx.fragment:fragment:" + Versions.androidx_fragment

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val lifecycle_compiler: String = "androidx.lifecycle:lifecycle-compiler:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.androidx_lifecycle

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val palette_ktx: String = "androidx.palette:palette-ktx:" + Versions.androidx_palette

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val palette: String = "androidx.palette:palette:" + Versions.androidx_palette

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val preference_ktx: String = "androidx.preference:preference-ktx:" +
            Versions.androidx_preference

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val preference: String = "androidx.preference:preference:" + Versions.androidx_preference

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val room_rxjava2: String = "androidx.room:room-rxjava2:" + Versions.androidx_room

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val swiperefreshlayout: String = "androidx.swiperefreshlayout:swiperefreshlayout:" +
            Versions.swiperefreshlayout

    const val viewpager2: String = "androidx.viewpager2:viewpager2:" + Versions.viewpager2

    /**
     * https://github.com/airbnb/lottie-android */
    const val lottie: String = "com.airbnb.android:lottie:" + Versions.lottie

    /**
     * https://developer.android.com/studio */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/facebook/stetho */
    const val stetho_okhttp3: String = "com.facebook.stetho:stetho-okhttp3:" +
            Versions.com_facebook_stetho

    /**
     * https://github.com/facebook/stetho */
    const val stetho_timber: String = "com.facebook.stetho:stetho-timber:" +
            Versions.com_facebook_stetho

    /**
     * https://github.com/facebook/stetho */
    const val stetho: String = "com.facebook.stetho:stetho:" + Versions.com_facebook_stetho

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://github.com/google/dagger */
    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

    const val firebase_database: String = "com.google.firebase:firebase-database:" +
            Versions.firebase_database

    /**
     * http://tools.android.com/ */
    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    /**
     * https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/ */
    const val retrofit2_kotlin_coroutines_adapter: String =
            "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:" +
            Versions.retrofit2_kotlin_coroutines_adapter

    /**
     * https://github.com/JakeWharton/RxBinding/ */
    const val rxbinding_design: String = "com.jakewharton.rxbinding2:rxbinding-design:" +
            Versions.com_jakewharton_rxbinding2

    /**
     * https://github.com/JakeWharton/RxBinding/ */
    const val rxbinding_support_v4: String = "com.jakewharton.rxbinding2:rxbinding-support-v4:" +
            Versions.com_jakewharton_rxbinding2

    /**
     * https://github.com/JakeWharton/RxBinding/ */
    const val rxbinding: String = "com.jakewharton.rxbinding2:rxbinding:" +
            Versions.com_jakewharton_rxbinding2

    const val rxrelay: String = "com.jakewharton.rxrelay2:rxrelay:" + Versions.rxrelay

    /**
     * https://github.com/JakeWharton/timber */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://github.com/mattprecious/telescope/ */
    const val telescope: String = "com.mattprecious.telescope:telescope:" + Versions.telescope

    /**
     * https://github.com/square/moshi */
    const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:" + Versions.moshi_kotlin

    /**
     * https://github.com/square/okhttp */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp */
    const val mockwebserver: String = "com.squareup.okhttp3:mockwebserver:" +
            Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okio/ */
    const val okio: String = "com.squareup.okio:okio:" + Versions.okio

    /**
     * https://github.com/square/retrofit/ */
    const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/ */
    const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/ */
    const val retrofit_mock: String = "com.squareup.retrofit2:retrofit-mock:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/ */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/uber/AutoDispose/ */
    const val autodispose: String = "com.uber.autodispose:autodispose:" + Versions.autodispose

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val android_junit5: String = "de.mannodermaus.gradle.plugins:android-junit5:" +
            Versions.android_junit5

    /**
     * http://mockk.io */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://github.com/ReactiveX/RxAndroid */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxJava */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * https://jax-ws.dev.java.net/ */
    const val jsr250_api: String = "javax.annotation:jsr250-api:" + Versions.jsr250_api

    /**
     * http://junit.org */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * http://assertj.org */
    const val assertj_core: String = "org.assertj:assertj-core:" + Versions.assertj_core

    /**
     * https://kotlinlang.org/ */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_noarg: String = "org.jetbrains.kotlin:kotlin-noarg:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
            Versions.org_jetbrains_kotlin

    const val ktlint_gradle: String = "org.jlleitschuh.gradle:ktlint-gradle:" +
            Versions.ktlint_gradle

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_vintage_engine: String = "org.junit.vintage:junit-vintage-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://github.com/mockito/mockito */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    /**
     * http://robolectric.org */
    const val robolectric: String = "org.robolectric:robolectric:" + Versions.robolectric

    const val mvrx: String = "com.airbnb.android:mvrx:" + Versions.mvrx
}
